# -*- coding: utf-8 -*-
"""(Train Data) Kenya_Clinical_Reasoning_Challenge_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1mUlcpvi1NfG5B02aM_KWzNstgNp2ti

**TRAIN DATA**

---


This notebook unvails suspected errors in the training (train_raw.csv) dataset

**Please note that the 'Original_Index' column was started from 1 not 0**
"""

import pandas as pd

# 1. Load the original CSV
df = pd.read_csv('/content/train_raw.csv')

# 2. Keep only the three columns you care about
df_selected = df[['Master_Index', 'Prompt', 'Clinician']]

# 3. List of row‐numbers (1‑based)
keep_1_based = [4,14,16,26,69,72,81,82,104,112,115,117,137,148,185,189,196,205,217,267,234,293,295,301,303,314,318,332,352,359,363,366,371,392,397]

# 4. Convert to 0‑based positions for .iloc
keep_0_based = [i - 1 for i in keep_1_based]

# 5. Extract those rows (copying to avoid SettingWithCopyWarning)
df_filtered = df_selected.iloc[keep_0_based].copy()

# 6. Add a new column “Original_Index” that reflects the 1‑based row number
df_filtered['Original_Index'] = keep_1_based

# 7. Reorder columns so that Original_Index comes first
df_filtered = df_filtered[['Original_Index', 'Master_Index', 'Prompt', 'Clinician']]

#8. Print dataframe
df_filtered

# 9. Define a function to strip off the first sentence:
def remove_first_sentence(text):
    parts = text.split('. ', 1)
    if len(parts) > 1:
        return parts[1]
    else:
        # if there’s no period, return an empty string
        return ''

# 10. Apply that to the 'Prompt' column
df_filtered['Prompt'] = df_filtered['Prompt'].apply(remove_first_sentence)

#11. Print striped dataframe
df_filtered

"""POTENTIAL PROBLEMS TO CHECK:

1.   SUSPECTED CONTEXT MISMATCH: 26,104,137,148,161,318,332,352,363,371,397
2.   SUSPECTED SPELLING ERRORS: 112,185,189,280,284,286,289
3.   SUSPECTED AGE MISMATCH: 4,14,26,69,72,81,82,104,115,117,137,148,163,168,161,280,284,289,359,363,366,371,392,397




"""