# -*- coding: utf-8 -*-
"""Complete_MVPInstall.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qND0VcgtQouYVmXRkTLgu3rexRRlxqzo

INSTALL LIBRARIES
"""

!pip install transformers datasets pandas torch rouge_score sentencepiece

!pip install accelerate

!pip install evaluate

"""IMPORT LIBRARIES"""

import os
import pandas as pd
import numpy as np
import string
import re
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    MvpTokenizer,
    MvpForConditionalGeneration,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    GenerationConfig,#########
    EarlyStoppingCallback,
)
from evaluate import load as load_metric

"""REMOVE MARKERS FUNCTION

*   Removes markers
*   Strip whitespace


"""

def clean_tagged_dataframe(
    df: pd.DataFrame,
    cols_to_clean: list = ["source", "target"],
    tags: list = None
) -> pd.DataFrame:
    """
    Remove predefined tags from specified text columns in a DataFrame.

    Args:
        df (pd.DataFrame): Input DataFrame.
        cols_to_clean (list of str): Column names to clean (default ["source","target"]).
        tags (list of regex strings): Tags to remove. If None, defaults to:
            [r'\[INTRO\]', r'\[QUES\]', r'\[VITALS\]', r'\[HIST\]', r'\[SYM\]'].

    Returns:
        pd.DataFrame: A copy of the DataFrame with the specified columns cleaned.
    """
    # Default tags if none provided
    if tags is None:
        tags = [r'\[INTRO\]',r'\[INRO\]', r'\[QUES\]', r'\[VITALS\]', r'\[HIST\]', r'\[SYM\]']
    pattern = "|".join(tags)

    df_clean = df.copy()
    cleaned_any = False

    for col in cols_to_clean:
        if col in df_clean.columns:
            # ensure text, strip tags & whitespace
            df_clean[col] = (
                df_clean[col]
                .astype(str)
                .str.replace(pattern, "", regex=True)
                .str.strip()
            )
            cleaned_any = True

    if not cleaned_any:
        raise ValueError(
            f"None of the columns {cols_to_clean} found in DataFrame. "
            f"Found columns: {list(df_clean.columns)}"
        )

    return df_clean

"""CLEAN TEXT FUNCTION


*   Removes unwanted items
*   Removes non-alphanumeric characters


"""

def clean_text(text: str) -> str:
    if not isinstance(text, str):
        return ""
    text = text.lower()
    # Replace '-' with a space
    text = text.replace("-", " ")
    text = text.replace("/", " ")
    text = text.replace("+", " ")
    text = text.replace("?", " ")
    text = text.replace("!", " ")
    text = text.replace(",", " ")
    text = text.replace(":", " ")
    text = text.replace(";", " ")
    text = text.replace("?"," ")
    text = text.replace("%", " ")
    text = text.replace("*"," ")
    text = text.replace("°C"," ")
    text = text.replace("."," ")
    # Remove punctuation
    translator = str.maketrans("", "", string.punctuation)
    text = text.translate(translator)
    # Remove any other non-alphanumeric characters
    text = re.sub(r"[^a-z0-9\s]", "", text)
    # Collapse whitespace
    text = re.sub(r"\s+", " ", text).strip()
    return text

"""LOAD DATA


*   Load datasets
*   Preview dataframes


"""

# 1. Load data
train_df = pd.read_csv("/content/extracted_marker_train_json_data_clean.csv").dropna(subset=["source","target"]).reset_index(drop=True)
test_df  = pd.read_csv("/content/extracted_marker_test_json_data_clean.csv").dropna(subset=["source"]).reset_index(drop=True)

train_df = clean_tagged_dataframe(train_df)
test_df = clean_tagged_dataframe(test_df)

train_df

test_df

test_df['source'] = test_df['source'].str.replace(r"[-\n]", " ", regex=True)
train_df['source'] = train_df['source'].str.replace(r"[-\n]", " ", regex=True)
train_df['target'] = train_df['target'].str.replace(r"[-\n]", " ", regex=True)

train_df

test_df

"""TRAIN TEST SPLIT

*   Split Test data
*   Split Train data


"""

from sklearn.model_selection import train_test_split

# Split train_df into train and test parts
train, test = train_test_split(
    train_df,
    test_size=0.2,        # 20% goes to test_df
    random_state=42,      # for reproducibility
    shuffle=True          # shuffle before splitting (default)
)

"""CONVERT DATAFRAMES INTO HUGGINGFACE DATASET FORMAT"""

hf_train = Dataset.from_pandas(train)
hf_test  = Dataset.from_pandas(test)

"""LOAD MODEL AND TOKENIZER"""

# 2. Tokenizer & Model
tokenizer = MvpTokenizer.from_pretrained("RUCAIBox/mvp")
model     = MvpForConditionalGeneration.from_pretrained("RUCAIBox/mtl-data-to-text")

"""CHECK MAXIMUM TOKEN COUNT IN SOURCE AND TAGET OF TRAIN/TEST"""

# from transformers import AutoTokenizer

# # Load the tokenizer you're using
# tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")

# Count tokens per example
train_df['source_token_count'] = train_df['source'].apply(lambda x: len(tokenizer.encode(x, truncation=False)))
train_df['target_token_count'] = train_df['target'].apply(lambda x: len(tokenizer.encode(x, truncation=False)))

# Get maximums
max_source_length = train_df['source_token_count'].max()
max_target_length = train_df['target_token_count'].max()

print(f"Max source length: {max_source_length} tokens")
print(f"Max target length: {max_target_length} tokens")

# Count tokens per example
test_df['source_token_count'] = test_df['source'].apply(lambda x: len(tokenizer.encode(x, truncation=False)))

# Get maximums
max_source_length_t = test_df['source_token_count'].max()

print(f"Max source length: {max_source_length_t} tokens")

# max_input_length  = 512 #512
# max_output_length = 256  #256 #128 # 256

"""SET MAXIMUM TOKEN: INPUT AND OUTPUT LENGTH"""

max_input_length  = 384    # >291, so no source will be truncated
max_output_length = 512    # covers your 500-token targets

"""PREPROCESSING FUNCION"""

# 3. Preprocessing fn
def preprocess_fn(batch):
    inputs = tokenizer(
        batch["source"],
        truncation=True,
        max_length=max_input_length,
        padding="max_length",
    )
    targets = tokenizer(
        batch["target"],
        truncation=True,
        max_length=max_output_length,
        padding="max_length",
    ) if "target" in batch else {}
    labels = targets.get("input_ids", None)
    # replace pad token id's in labels by -100 so they are ignored by loss
    if labels is not None:
        labels = [
            [(l if l != tokenizer.pad_token_id else -100) for l in lab]
            for lab in labels
        ]
    return {
        **inputs,
        **({"labels": labels} if labels is not None else {}),
    }

"""APPLY PREPROCESSING FUNCTION"""

# from datasets import DatasetDict

tokenized_datasets = DatasetDict({
    "train": hf_train.map(
        preprocess_fn,
        batched=True,
        remove_columns=hf_train.column_names
    ),
    "eval": hf_test.map(
        preprocess_fn,
        batched=True,
        remove_columns=hf_test.column_names
    ),
})

"""DATA COLLATOR"""

# 5. Data collator
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

"""ROUGE METRIC"""

# 6. Load ROUGE
rouge = load_metric("rouge")

"""ROUGE METRIC FUNCTION"""

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)

    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in predictions]
    result["gen_len"] = np.mean(prediction_lens)

    return {k: round(v, 4) for k, v in result.items()}

"""CUDA CLEAR CACHE


*   Had a few memory issues
*   Did not have good resources


"""

import torch
torch.cuda.empty_cache()

# training_args = Seq2SeqTrainingArguments(
#     # ← your generation settings bundled here
#     generation_config=GenerationConfig(
#         decoder_start_token_id=tokenizer.pad_token_id,
#         max_length=512,           # allow up to 512 tokens in the answer
#         min_length=256,           # ensure at least 128 tokens are produced
#         length_penalty=1.2,       # discourage too-short outputs
#         num_beams=4,              # use beam search for more coherent long output
#         no_repeat_ngram_size=3,   # avoid repeating the same 3-gram
#         early_stopping=True,      # stop once all beams finish
#     ),

#     output_dir="mvp-models",

#     # → epoch-based evaluation & checkpointing
#     eval_strategy="epoch",    # run eval at the end of each epoch
#     save_strategy="epoch",          # save a checkpoint at the end of each epoch
#     logging_strategy="epoch",
#     load_best_model_at_end=True,    # after training, reload the best checkpoint on your metric
#     metric_for_best_model="eval_rouge1",  # or whichever ROUGE key you prefer
#     greater_is_better=True,              # for ROUGE f‑scores

#     per_device_train_batch_size=4,
#     per_device_eval_batch_size=4,
#     gradient_accumulation_steps=4,  # or more
#     learning_rate=5e-5,
#     weight_decay=0.01,
#     num_train_epochs=20,

#     predict_with_generate=True,         # enable generation during eval
#     #generation_max_length=512,          # passed to model.generate()
#     #generation_num_beams=4,             # passed to model.generate()
#     #fp16=True,                          # if you have a GPU
#     push_to_hub=False,
#     report_to="none",
#     #torch_compile=False,           # disable torch.compile calls inside Trainer
# )

"""SEQ2SEQ TRAIN ARGS SETUP"""

training_args = Seq2SeqTrainingArguments(

    # generation_config=GenerationConfig(
    #     decoder_start_token_id=tokenizer.pad_token_id,
    #     max_length=512,           # allow up to 512 tokens in the answer
    #     min_length=256,           # *256 ensure at least 256 tokens are produced
    #     length_penalty=1.2,       # discourage too-short outputs
    #     num_beams=4,              # use beam search for more coherent long output
    #     no_repeat_ngram_size=3,   # avoid repeating the same 3-gram
    #     early_stopping=True,      # stop once all beams finish
    # ),

    # → step-based evaluation & checkpointing
    eval_strategy="steps",    # run eval at the end of each epoch
    save_strategy="steps",          # save a checkpoint at the end of each epoch
    logging_strategy="steps",
    output_dir="model-mvp",
    load_best_model_at_end=True,    # after training, reload the best checkpoint on your metric
    eval_steps=500,
    logging_steps=100,
    save_steps=500,
    save_total_limit=2,
    metric_for_best_model="eval_rouge1",  # or whichever ROUGE key you prefer
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    learning_rate=5e-5,
    weight_decay=0.01,
    num_train_epochs=20,

    predict_with_generate=True,         # enable generation during eval
    #fp16=True,                          # if you have a GPU
    push_to_hub=False,
    report_to="none",

)

# 8. Trainer
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset= tokenized_datasets["eval"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,     # use ROUGE
    callbacks=[
        EarlyStoppingCallback(early_stopping_patience=5, early_stopping_threshold=0.001)
    ]
)

"""ENABLE MODEL GRADIENT CHECKPOINTING"""

model.gradient_checkpointing_enable()  # at model instantiation

"""TRAIN MODEL"""

# 9. Train + evaluate
trainer.train()
# during evaluation steps, trainer will:
#   * call model.generate(...) with your beam/length settings
#   * compute ROUGE on the generated outputs

"""METRICS"""

# 10. Final evaluation on held-out eval split
metrics = trainer.evaluate()
print("Eval metrics:", metrics)

"""APPLY PREDICTIONS ON TEST DATAFRAME"""

# 11. Inference on test set
model.eval()
all_preds = []
batch_size = 8
for i in range(0, len(test_df), batch_size):
    batch_src = test_df["source"].iloc[i : i + batch_size].tolist()
    inputs = tokenizer(
        batch_src,
        return_tensors="pt",
        truncation=True,
        max_length=max_input_length,
        padding="longest",
    ).to(trainer.args.device)

    generated_ids = model.generate(
        inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_length=256,           # match your target length
        min_length=80,            # avoid too‑short outputs
        length_penalty=1.2,       # encourage full summarization
        num_beams=10,              # more thorough search
        no_repeat_ngram_size=3,   # reduce loops
        early_stopping=True,
        bad_words_ids=[[tokenizer.encode(w)[0]] for w in ["basically", "actually", "..."]]
    )
    preds = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
    all_preds.extend(preds)

"""GENERATE SUBMISSION FILE"""

test_raw_df = pd.read_csv('/content/test_raw.csv')

master_index = test_raw_df[['Master_Index']]

master_index

# 12. Export submission
submission = test_df.copy()
submission["Clinician"] = all_preds
submission["Master_Index"] = master_index['Master_Index']

submission = submission[["Master_Index",'source',"Clinician"]]
submission.to_csv("source_ stest_submission_tests.csv", index=False)
print("Saved submission.csv with", len(submission), "rows.")

# from google.colab import drive
# drive.mount('/content/drive')

#!cp -r /content/model-mvp /content/drive/MyDrive/